<a href="https://colab.research.google.com/github/shumrutha/240901104-python/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#flattening
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
flarr=arr.flatten()
print("\n Original array : \n",arr)
print("\n Flatten array:\n",flarr)




 Original array : 
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Flatten array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\n No.of dimentions : \n",arr.ndim)
print("\n shape of array : \n",arr.shape)
print("\n size of array : \n",arr.size)
print("\n Array type : \n",arr.dtype)

newtype=arr.astype('f')

print("\n converted array element : \n",newtype)
print("\n converted array type : \n",newtype.dtype)


 No.of dimentions : 
 2

 shape of array : 
 (3, 4)

 size of array : 
 12

 Array type : 
 int64

 converted array element : 
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

 converted array type : 
 float32


In [4]:
#slicing
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2:,2:])
print(p[3:,3:])


[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[[ 9]
 [12]
 [15]]
[]
